spring.application.name=movie-ticket-booking-backend

# SERVER (RENDER SAFE)
server.port=${PORT:8080}

# MONGODB
spring.data.mongodb.uri=mongodb+srv://ravivarma7939_db_user:abcdef123@jonsnow.mlyifw5.mongodb.net/?retryWrites=true&w=majority&appName=JonSnow

spring.data.mongodb.database=movieticket_db


# ===============================
# JWT CONFIG
# ===============================
jwt.secret=12345678901234567890123456789012
jwt.expirationMs=86400000


# ===============================
# CLOUDINARY CONFIG (FIXED KEYS)
# ===============================
cloudinary.cloudName=drhjhrsxi
cloudinary.apiKey=195725628726872
cloudinary.apiSecret=GMAtYukm3Mgs0ZaPb0vg-mgUZ3M

# ===============================
# FILE UPLOAD CONFIG
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# RAZORPAY CONFIG (FIXED KEYS)
# ===============================
razorpay.keyId=rzp_test_SYgPOcz1r0tEhg
razorpay.keySecret=WmLOKDmX1xkonUQR7BPtkmk7

# ===============================
# EMAIL CONFIG (SMTP - Gmail)
# ===============================
# ===============================
# EMAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ravivarma7939@gmail.com
spring.mail.password=qcngxaayfdtmprtg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# SWAGGER (SPRINGDOC)
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.movieticket=DEBUG

# ===============================
# SCHEDULER
# ===============================
spring.task.scheduling.pool.size=5





