# ===============================
# APPLICATION
# ===============================
spring.application.name=movie-ticket-booking-backend
server.port=${PORT:8080}
# ===============================
# MONGODB (RENDER / ATLAS)
# ===============================
spring.data.mongodb.uri=mongodb+srv://ravivarma7939_db_user:abcdef123@jonsnow.mlyifw5.mongodb.net/ecommerce_db?retryWrites=true&w=majority&appName=JonSnow

# ===============================
# ===============================
# JWT
# ===============================
jwt.secret=mysupersecuresecretkeymysupersecuresecretkey1234567890
jwt.expirationMs=86400000

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud-name=drhjhrsxi
cloudinary.api-key=195725628726872
cloudinary.api-secret=GMAtYukm3Mgs0ZaPb0vg-mgUZZ3M

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# RAZORPAY
# ===============================
razorpay.key_id=rzp_test_SYgPOcz1r0tEhg
razorpay.key_secret=WmLOKDmX1xkonUQR7BPtkmk7

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.com.ecommerce=DEBUG

# ===============================
# SCHEDULER
# ===============================
spring.task.scheduling.pool.size=5



